/**
 * Complete German → English Pokémon name mapping.
 * Generated from PokeAPI GraphQL (https://beta.pokeapi.co/graphql/v1beta)
 * plus hand-curated entries for paradox forms, ultra beasts, and OCR variants.
 * 855 entries total.
 *
 * Keys are lowercase German names for case-insensitive lookup.
 * Only contains entries where the German name differs from the English name.
 */
export const DE_TO_EN: Record<string, string> = {
  "rexblisar": "Abomasnow",
  "hydragil": "Accelgor",
  "durengard": "Aegislash",
  "stolloss": "Aggron",
  "griffel": "Aipom",
  "simsala": "Alakazam",
  "pokusan": "Alcremie",
  "mamolida": "Alomomola",
  "amarino": "Amaura",
  "ambidiffel": "Ambipom",
  "hutsassa": "Amoonguss",
  "epitaff": "Annihilape",
  "schlapfel": "Appletun",
  "knapfel": "Applin",
  "aranestro": "Araquanid",
  "olithena": "Arboliva",
  "arkani": "Arcanine",
  "briduradon": "Archaludon",
  "flapteryx": "Archen",
  "aeropteryx": "Archeops",
  "cryospino": "Arctibax",
  "pescryodon": "Arctovish",
  "lecryodon": "Arctozolt",
  "crimanzo": "Armarouge",
  "parfinesse": "Aromatisse",
  "stollunior": "Aron",
  "pikuda": "Arrokuda",
  "arktos": "Articuno",
  "ohrdoch": "Audino",
  "amagarga": "Aurorus",
  "arktilas": "Avalugg",
  "milza": "Axew",
  "tobutz": "Azelf",
  "kindwurm": "Bagon",
  "puppance": "Baltoy",
  "thanathora": "Barbaracle",
  "schmerbe": "Barboach",
  "barrakiefa": "Barraskewda",
  "salmagnis": "Basculegion",
  "barschuft": "Basculin",
  "bollterus": "Bastiodon",
  "espinodon": "Baxcalibur",
  "lorblatt": "Bayleef",
  "siberio": "Beartic",
  "papinella": "Beautifly",
  "bibor": "Beedrill",
  "megalon": "Beheeyem",
  "tanhel": "Beldum",
  "wampitz": "Bellibolt",
  "blubella": "Bellossom",
  "knofensa": "Bellsprout",
  "arktip": "Bergmite",
  "kosturso": "Bewear",
  "bidifas": "Bibarel",
  "bidiza": "Bidoof",
  "bithora": "Binacle",
  "caesurio": "Bisharp",
  "kopplosio": "Blacephalon",
  "turtok": "Blastoise",
  "lohgock": "Blaziken",
  "sensect": "Blipbug",
  "heiteira": "Blissey",
  "elezeba": "Blitzle",
  "sedimantur": "Boldore",
  "bellektro": "Boltund",
  "adebom": "Bombirdier",
  "mobai": "Bonsly",
  "bisofank": "Bouffalant",
  "frubberl": "Bounsweet",
  "rutena": "Braixen",
  "horrerba": "Brambleghast",
  "weherba": "Bramblin",
  "washakwil": "Braviary",
  "kapilz": "Breloom",
  "marikeck": "Brionne",
  "bronzel": "Bronzor",
  "wutpilz": "Brute Bonnet",
  "knirfish": "Bruxish",
  "knospi": "Budew",
  "bamelin": "Buizel",
  "bisasam": "Bulbasaur",
  "haspiror": "Buneary",
  "scoppel": "Bunnelby",
  "smettbo": "Butterfree",
  "masskito": "Buzzwole",
  "tuska": "Cacnea",
  "noktuska": "Cacturne",
  "coronospa": "Calyrex",
  "chilingel": "Capsakid",
  "rocara": "Carbink",
  "wagong": "Carkol",
  "venuflibis": "Carnivine",
  "karippas": "Carracosta",
  "kanivanha": "Carvanha",
  "panekon": "Cascoon",
  "formeo": "Castform",
  "raupy": "Caterpie",
  "kaguron": "Celesteela",
  "infernopod": "Centiskorch",
  "azugladis": "Ceruledge",
  "kolowal": "Cetitan",
  "flaniwal": "Cetoddle",
  "skelabra": "Chandelure",
  "chaneira": "Chansey",
  "knarbon": "Charcadet",
  "glurak": "Charizard",
  "akkup": "Charjabug",
  "glumanda": "Charmander",
  "glutexo": "Charmeleon",
  "plaudagei": "Chatot",
  "kinoso": "Cherrim",
  "kikugi": "Cherubi",
  "brigaron": "Chesnaught",
  "igamaro": "Chespin",
  "kamehaps": "Chewtle",
  "yuyu": "Chi-Yu",
  "baojian": "Chien-Pao",
  "endivie": "Chikorita",
  "panflam": "Chimchar",
  "palimpalim": "Chimecho",
  "lampi": "Chinchou",
  "klingplim": "Chingling",
  "chillabell": "Cinccino",
  "liberlo": "Cinderace",
  "perlu": "Clamperl",
  "scampisto": "Clauncher",
  "wummer": "Clawitzer",
  "lepumentas": "Claydol",
  "pixi": "Clefable",
  "piepi": "Clefairy",
  "pii": "Cleffa",
  "klopptopus": "Clobbopus",
  "suelord": "Clodsire",
  "austos": "Cloyster",
  "montecarbo": "Coalossal",
  "kobalium": "Cobalion",
  "echnatoll": "Cofagrigus",
  "wadribie": "Combee",
  "jungglut": "Combusken",
  "curelei": "Comfey",
  "meistagrif": "Conkeldurr",
  "patinaraja": "Copperajah",
  "krebscorps": "Corphish",
  "corasonn": "Corsola",
  "krarmor": "Corviknight",
  "kranoviz": "Corvisquire",
  "cosmovum": "Cosmoem",
  "waumboll": "Cottonee",
  "krawell": "Crabominable",
  "krabbox": "Crabrawler",
  "wielie": "Cradily",
  "urgl": "Cramorant",
  "koknodon": "Cranidos",
  "krebutack": "Crawdaunt",
  "glibunkel": "Croagunk",
  "iksbat": "Crobat",
  "lokroko": "Crocalor",
  "tyracroc": "Croconaw",
  "castellith": "Crustle",
  "frigometri": "Cryogonal",
  "petznief": "Cubchoo",
  "tragosso": "Cubone",
  "kupfanti": "Cufant",
  "gorgasonn": "Cursola",
  "wommel": "Cutiefly",
  "mopex": "Cyclizar",
  "feurigel": "Cyndaquil",
  "backel": "Dachsbun",
  "flampivian": "Darmanitan",
  "arboretoss": "Dartrix",
  "flampion": "Darumaka",
  "silvarro": "Decidueye",
  "sesokitz": "Deerling",
  "kapuno": "Deino",
  "enekoro": "Delcatty",
  "botogel": "Delibird",
  "fennexis": "Delphox",
  "jugong": "Dewgong",
  "zwottronin": "Dewott",
  "araqua": "Dewpider",
  "moruda": "Dhelmise",
  "grebbit": "Diggersby",
  "digda": "Diglett",
  "sirapfel": "Dipplin",
  "dodri": "Dodrio",
  "dodu": "Doduo",
  "olivinio": "Dolliv",
  "heerashai": "Dondozo",
  "keradar": "Dottler",
  "duokles": "Doublade",
  "pescragon": "Dracovish",
  "lectragon": "Dracozolt",
  "tandrak": "Dragalge",
  "katapuldra": "Dragapult",
  "dragonir": "Dragonair",
  "dragoran": "Dragonite",
  "phandra": "Drakloak",
  "sen-long": "Drampa",
  "piondragi": "Drapion",
  "kamalm": "Drednaw",
  "grolldra": "Dreepy",
  "drifzepeli": "Drifblim",
  "driftlon": "Drifloon",
  "rotomurf": "Drilbur",
  "phlegleon": "Drizzile",
  "traumato": "Drowzee",
  "shardrago": "Druddigon",
  "zwollock": "Dubwool",
  "piccolente": "Ducklett",
  "dummimisel": "Dudunsparce",
  "digdri": "Dugtrio",
  "dummisel": "Dunsparce",
  "mitodos": "Duosion",
  "fermicula": "Durant",
  "zwirrklop": "Dusclops",
  "zwirrfinst": "Dusknoir",
  "zwirrlicht": "Duskull",
  "pudox": "Dustox",
  "lithomith": "Dwebble",
  "zapplalek": "Eelektrik",
  "zapplarang": "Eelektross",
  "evoli": "Eevee",
  "kubuin": "Eiscue",
  "rettan": "Ekans",
  "cottomi": "Eldegoss",
  "elektek": "Electabuzz",
  "elevoltek": "Electivire",
  "frizelbliz": "Electrike",
  "lektrobal": "Electrode",
  "pygraulon": "Elgyem",
  "flambirex": "Emboar",
  "impoleon": "Empoleon",
  "cupidos": "Enamorus",
  "cavalanzas": "Escavalier",
  "psiopatra": "Espathra",
  "psiana": "Espeon",
  "psiau": "Espurr",
  "endynalos": "Eternatus",
  "stalobor": "Excadrill",
  "owei": "Exeggcute",
  "kokowei": "Exeggutor",
  "krawumms": "Exploud",
  "legios": "Falinks",
  "porenta": "Farfetch’d",
  "ibitak": "Fearow",
  "barschwa": "Feebas",
  "fynx": "Fennekin",
  "impergator": "Feraligatr",
  "kastadur": "Ferroseed",
  "tentantel": "Ferrothorn",
  "beatori": "Fezandipiti",
  "hefel": "Fidough",
  "normifin": "Finizen",
  "waaty": "Flaaffy",
  "flaminkno": "Flamigo",
  "drapfel": "Flapple",
  "flamara": "Flareon",
  "dartignis": "Fletchinder",
  "dartiri": "Fletchling",
  "flattutu": "Flittle",
  "bojelin": "Floatzel",
  "feliospa": "Floragato",
  "flatterhaar": "Flutter Mane",
  "libelldra": "Flygon",
  "imantis": "Fomantis",
  "tarnpignon": "Foongus",
  "forstellka": "Forretress",
  "sharfax": "Fraxure",
  "frospino": "Frigibax",
  "quabbel": "Frillish",
  "froxy": "Froakie",
  "amphizel": "Frogadier",
  "frosdedje": "Froslass",
  "mottineva": "Frosmoth",
  "krokel": "Fuecoco",
  "coiffwaff": "Furfrou",
  "wiesenior": "Furret",
  "knarksel": "Gabite",
  "galagladi": "Gallade",
  "voltula": "Galvantula",
  "deponitox": "Garbodor",
  "knakrack": "Garchomp",
  "guardevoir": "Gardevoir",
  "saltigant": "Garganacl",
  "nebulak": "Gastly",
  "kleinstein": "Geodude",
  "monetigo": "Gholdengo",
  "kaumalat": "Gible",
  "brockoloss": "Gigalith",
  "gierspenst": "Gimmighoul",
  "glaziola": "Glaceon",
  "firnontor": "Glalie",
  "charmian": "Glameow",
  "polaross": "Glastrier",
  "skorgla": "Gligar",
  "lumispross": "Glimmet",
  "lumiflora": "Glimmora",
  "skorgro": "Gliscor",
  "duflor": "Gloom",
  "chevrumm": "Gogoat",
  "goldini": "Goldeen",
  "entoron": "Golduck",
  "geowaz": "Golem",
  "golbit": "Golett",
  "tectass": "Golisopod",
  "golgantes": "Golurk",
  "viscogon": "Goodra",
  "viscora": "Goomy",
  "saganabyss": "Gorebyss",
  "cottini": "Gossifleur",
  "mollimorba": "Gothita",
  "morbitesse": "Gothitelle",
  "hypnomorba": "Gothorita",
  "keilflamme": "Gouging Fire",
  "pumpdjinn": "Gourgeist",
  "affiti": "Grafaiai",
  "kaocto": "Grapploct",
  "georok": "Graveler",
  "riesenzahn": "Great Tusk",
  "gruff": "Greavard",
  "schlaraffel": "Greedent",
  "quajutsu": "Greninja",
  "sleima": "Grimer",
  "olangaar": "Grimmsnarl",
  "chimpep": "Grookey",
  "chelcarain": "Grotle",
  "reptain": "Grovyle",
  "fukano": "Growlithe",
  "mabula": "Grubbin",
  "groink": "Grumpig",
  "schluppuck": "Gulpin",
  "manguspektor": "Gumshoos",
  "strepoli": "Gurdurr",
  "schlingking": "Guzzlord",
  "garados": "Gyarados",
  "mediras": "Hakamo-o",
  "wonneira": "Happiny",
  "brimova": "Hatenna",
  "silembrim": "Hatterene",
  "brimano": "Hattrem",
  "alpollo": "Haunter",
  "resladero": "Hawlucha",
  "maxax": "Haxorus",
  "furnifraß": "Heatmor",
  "elezard": "Heliolisk",
  "eguana": "Helioptile",
  "skaraborn": "Heracross",
  "terribark": "Herdier",
  "hippoterus": "Hippowdon",
  "nockchan": "Hitmonchan",
  "kicklee": "Hitmonlee",
  "kapoera": "Hitmontop",
  "ho-oh": "Ho-Oh",
  "kramshef": "Honchkrow",
  "gramokles": "Honedge",
  "hoppspross": "Hoppip",
  "seeper": "Horsea",
  "hundemon": "Houndoom",
  "hunduster": "Houndour",
  "friedwuff": "Houndstone",
  "aalabyss": "Huntail",
  "hydrapfel": "Hydrapple",
  "trikephalo": "Hydreigon",
  "fluffeluff": "Igglybuff",
  "bähmon": "Impidimp",
  "fuegro": "Incineroar",
  "servol": "Indeedee",
  "panferno": "Infernape",
  "iscalar": "Inkay",
  "intelleon": "Inteleon",
  "eisenfels": "Iron Boulder",
  "eisenbündel": "Iron Bundle",
  "eisenhaupt": "Iron Crown",
  "eisenkrone": "Iron Crown",
  "eisenhand": "Iron Hands",
  "eisenhals": "Iron Jugulis",
  "eisenblatt": "Iron Leaves",
  "eisenfalter": "Iron Moth",
  "eisendorn": "Iron Thorns",
  "eisenrad": "Iron Treads",
  "eisenblüte": "Iron Valiant",
  "eisenkrieger": "Iron Valiant",
  "bisaknosp": "Ivysaur",
  "miniras": "Jangmo-o",
  "apoquallyp": "Jellicent",
  "pummeluff": "Jigglypuff",
  "blitza": "Jolteon",
  "wattzapf": "Joltik",
  "papungha": "Jumpluff",
  "rossana": "Jynx",
  "kokuna": "Kakuna",
  "kangama": "Kangaskhan",
  "laukaps": "Karrablast",
  "katagami": "Kartana",
  "voltrean": "Kilowattrel",
  "gladimperio": "Kingambit",
  "seedraking": "Kingdra",
  "kliklak": "Klang",
  "klibbe": "Klawf",
  "axantor": "Kleavor",
  "clavion": "Klefki",
  "klikk": "Klink",
  "klikdiklak": "Klinklang",
  "smogon": "Koffing",
  "koalelu": "Komala",
  "grandiras": "Kommo-o",
  "zirpurze": "Kricketot",
  "zirpeise": "Kricketune",
  "rokkaiman": "Krokorok",
  "rabigator": "Krookodile",
  "dakuma": "Kubfu",
  "stollrak": "Lairon",
  "laternecto": "Lampent",
  "demeteros": "Landorus",
  "ignivor": "Larvesta",
  "folipurba": "Leafeon",
  "matrifol": "Leavanny",
  "ferkuli": "Lechonk",
  "schlurplek": "Lickilicky",
  "schlurp": "Lickitung",
  "kleoparda": "Liepard",
  "liliep": "Lileep",
  "dressella": "Lilligant",
  "yorkleff": "Lillipup",
  "geradaks": "Linoone",
  "leufeo": "Litleo",
  "flamiau": "Litten",
  "lichtel": "Litwick",
  "lextremo": "Lokix",
  "lombrero": "Lombre",
  "schlapor": "Lopunny",
  "loturzel": "Lotad",
  "krakeelo": "Loudred",
  "kappalores": "Ludicolo",
  "lunastein": "Lunatone",
  "mantidea": "Lurantis",
  "liebiskus": "Luvdisc",
  "luxtra": "Luxray",
  "wolwerock": "Lycanroc",
  "mastifioso": "Mabosstiff",
  "machomei": "Machamp",
  "maschock": "Machoke",
  "machollo": "Machop",
  "karpador": "Magikarp",
  "magbrant": "Magmortar",
  "magnetilo": "Magnemite",
  "calamanero": "Malamar",
  "mamutel": "Mamoswine",
  "grypheldis": "Mandibuzz",
  "voltenso": "Manectric",
  "mankey": "Mankey",
  "menki": "Mankey",
  "mantax": "Mantine",
  "mantirps": "Mantyke",
  "maracamba": "Maractus",
  "garstella": "Mareanie",
  "voltilamm": "Mareep",
  "knogga": "Marowak",
  "moorabbel": "Marshtomp",
  "mobtiff": "Maschiff",
  "maskeregen": "Masquerain",
  "famieps": "Maushold",
  "flunkifer": "Mawile",
  "meditalis": "Medicham",
  "meditie": "Meditite",
  "meganie": "Meganium",
  "maskagato": "Meowscarada",
  "psiaugon": "Meowstic",
  "mauzi": "Meowth",
  "vesprit": "Mesprit",
  "safcon": "Metapod",
  "mewtu": "Mewtwo",
  "lin-fu": "Mienfoo",
  "wie-shu": "Mienshao",
  "magnayen": "Mightyena",
  "hokumil": "Milcery",
  "mime jr": "Mime Jr.",
  "mime jr.": "Mime Jr.",
  "pantimimi": "Mime Jr.",
  "mimigma": "Mimikyu",
  "picochilla": "Minccino",
  "meteno": "Minior",
  "traunfugil": "Misdreavus",
  "traunmagil": "Mismagius",
  "lavados": "Moltres",
  "panpyro": "Monferno",
  "bubungus": "Morelull",
  "pelzebub": "Morgrem",
  "moterpel": "Mothim",
  "mr mime": "Mr. Mime",
  "mr. mime": "Mr. Mime",
  "pantimos": "Mr. Mime",
  "pantifrost": "Mr. Rime",
  "pampuli": "Mudbray",
  "hydropi": "Mudkip",
  "pampross": "Mudsdale",
  "sleimok": "Muk",
  "mampfaxo": "Munchlax",
  "benesaru": "Munkidori",
  "somniam": "Munna",
  "kramurx": "Murkrow",
  "somnivora": "Musharna",
  "geosali": "Nacli",
  "sedisal": "Naclstack",
  "agoyon": "Naganadel",
  "kleptifux": "Nickit",
  "anego": "Nihilego",
  "ninetales": "Ninetales",
  "vulnona": "Ninetales",
  "noctuh": "Noctowl",
  "ef-em": "Noibat",
  "uhafnir": "Noivern",
  "nasgnet": "Nosepass",
  "camaub": "Numel",
  "blanas": "Nuzleaf",
  "micrick": "Nymble",
  "barrikadax": "Obstagoon",
  "myrapla": "Oddish",
  "fragrunz": "Oinkologne",
  "boninu": "Okidogi",
  "amonitas": "Omanyte",
  "amoroso": "Omastar",
  "kommandutan": "Oranguru",
  "maritellit": "Orbeetle",
  "choreogel": "Oricorio",
  "schlurm": "Orthworm",
  "ottaro": "Oshawott",
  "myriador": "Overqwil",
  "delfinator": "Palafin",
  "colossand": "Palossand",
  "mebrana": "Palpitoad",
  "pam-pam": "Pancham",
  "pandagro": "Pangoro",
  "sodamak": "Panpour",
  "vegimak": "Pansage",
  "grillmak": "Pansear",
  "parasek": "Parasect",
  "quartermak": "Passimian",
  "nagelotz": "Patrat",
  "pamo": "Pawmi",
  "pamamo": "Pawmo",
  "pamomamo": "Pawmot",
  "gladiantri": "Pawniard",
  "infamomo": "Pecharunt",
  "mauzinger": "Perrserker",
  "snobilikat": "Persian",
  "lilminip": "Petilil",
  "paragoni": "Phantump",
  "schabelle": "Pheromosa",
  "tauboss": "Pidgeot",
  "tauboga": "Pidgeotto",
  "taubsi": "Pidgey",
  "dusselgurr": "Pidove",
  "ferkokel": "Pignite",
  "peppeck": "Pikipek",
  "keifel": "Piloswine",
  "britzigel": "Pincurchin",
  "tannza": "Pineco",
  "plinfa": "Piplup",
  "venicro": "Poipole",
  "quaxo": "Politoed",
  "quapsel": "Poliwag",
  "quaputzi": "Poliwhirl",
  "quappo": "Poliwrath",
  "mortcha": "Poltchageist",
  "mortipot": "Polteageist",
  "ponita": "Ponyta",
  "fiffyen": "Poochyena",
  "robball": "Popplio",
  "porygon z": "Porygon-Z",
  "porygon-z": "Porygon-Z",
  "primarene": "Primarina",
  "rasaff": "Primeape",
  "pliprin": "Prinplup",
  "voluminas": "Probopass",
  "enton": "Psyduck",
  "irrbis": "Pumpkaboo",
  "felilou": "Purrloin",
  "shnurgarst": "Purugly",
  "pyroleo": "Pyroar",
  "gufa": "Pyukumuku",
  "morlord": "Quagsire",
  "bailonda": "Quaquaval",
  "kwaks": "Quaxly",
  "fuentente": "Quaxwell",
  "igelavar": "Quilava",
  "igastarnish": "Quilladin",
  "baldorfish": "Qwilfish",
  "kickerlo": "Raboot",
  "skarabaks": "Rabsca",
  "furienblitz": "Raging Bolt",
  "tobelblitz": "Raging Bolt",
  "trasla": "Ralts",
  "rameidon": "Rampardos",
  "gallopa": "Rapidash",
  "rattikarl": "Raticate",
  "rattfratz": "Rattata",
  "relluk": "Rellor",
  "zytomega": "Reuniclus",
  "knattatox": "Revavroom",
  "rizeros": "Rhydon",
  "rihorn": "Rhyhorn",
  "rihornior": "Rhyperior",
  "bandelby": "Ribombee",
  "gortrom": "Rillaboom",
  "brüllmond": "Roaring Moon",
  "donnersichel": "Roaring Moon",
  "wuffels": "Rockruff",
  "kiesling": "Roggenrola",
  "klonkett": "Rolycoly",
  "meikro": "Rookidee",
  "bauz": "Rowlet",
  "geronimatz": "Rufflet",
  "oghnatoll": "Runerigus",
  "zobiris": "Sableye",
  "brutalanda": "Salamence",
  "molunk": "Salandit",
  "amfira": "Salazzle",
  "admurai": "Samurott",
  "sanaconda": "Sandaconda",
  "ganovil": "Sandile",
  "sandan": "Sandshrew",
  "sandamer": "Sandslash",
  "sandfell": "Sandy Shocks",
  "sankabuh": "Sandygast",
  "karadonis": "Sawk",
  "kronjuwild": "Sawsbuck",
  "purmel": "Scatterbug",
  "gewaldro": "Sceptile",
  "scherox": "Scizor",
  "cerapendra": "Scolipede",
  "hopplo": "Scorbunny",
  "halupenjo": "Scovillain",
  "irokex": "Scrafty",
  "zurrokex": "Scraggy",
  "brüllschweif": "Scream Tail",
  "sichlor": "Scyther",
  "seemon": "Seadra",
  "golking": "Seaking",
  "seejong": "Sealeo",
  "samurzel": "Seedot",
  "jurob": "Seel",
  "branawarz": "Seismitoad",
  "wiesor": "Sentret",
  "serpiroyal": "Serperior",
  "efoserp": "Servine",
  "vipitis": "Seviper",
  "strawickl": "Sewaddle",
  "tohaido": "Sharpedo",
  "ninjatom": "Shedinja",
  "draschel": "Shelgon",
  "muschas": "Shellder",
  "schalellos": "Shellos",
  "schnuthelm": "Shelmet",
  "schilterus": "Shieldon",
  "tengulist": "Shiftry",
  "lamellux": "Shiinotic",
  "sheinux": "Shinx",
  "sproxi": "Shroodle",
  "knilz": "Shroomish",
  "pottrott": "Shuckle",
  "symvolara": "Sigilyph",
  "schaloko": "Silcoon",
  "salanga": "Silicobra",
  "amigento": "Silvally",
  "sodachita": "Simipour",
  "vegichita": "Simisage",
  "grillchita": "Simisear",
  "fatalitcha": "Sinistcha",
  "fatalitee": "Sinistea",
  "lauchzelot": "Sirfetch’d",
  "thermopod": "Sizzlipede",
  "panzaeron": "Skarmory",
  "skelokrok": "Skeledirge",
  "mähikel": "Skiddo",
  "hubelupf": "Skiploom",
  "eneco": "Skitty",
  "pionskora": "Skorupi",
  "algitt": "Skrelp",
  "raffel": "Skwovet",
  "letarking": "Slaking",
  "bummelz": "Slakoth",
  "viscargot": "Sliggoo",
  "kriechflügel": "Slither Wing",
  "lahmus": "Slowbro",
  "laschoking": "Slowking",
  "flegmon": "Slowpoke",
  "schneckmag": "Slugma",
  "sabbaione": "Slurpuff",
  "farbeagle": "Smeargle",
  "olini": "Smoliv",
  "kussilla": "Smoochum",
  "sniebel": "Sneasel",
  "snieboss": "Sneasler",
  "serpifeu": "Snivy",
  "snomnom": "Snom",
  "relaxo": "Snorlax",
  "schneppke": "Snorunt",
  "shnebedeck": "Snover",
  "memmeon": "Sobble",
  "monozyto": "Solosis",
  "sonnfel": "Solrock",
  "habitak": "Spearow",
  "phantoross": "Spectrier",
  "puponcho": "Spewpa",
  "seemops": "Spheal",
  "spinsidias": "Spidops",
  "webarak": "Spinarak",
  "pandir": "Spinda",
  "kryppuk": "Spiritomb",
  "felori": "Sprigatito",
  "parfi": "Spritzee",
  "krawalloro": "Squawkabilly",
  "schiggy": "Squirtle",
  "muramura": "Stakataka",
  "damhirplex": "Stantler",
  "staralili": "Starly",
  "sterndu": "Staryu",
  "stahlos": "Steelix",
  "frubaila": "Steenee",
  "humanolith": "Stonjourner",
  "bissbark": "Stoutland",
  "velursi": "Stufful",
  "flunschlik": "Stunfisk",
  "skunkapuh": "Stunky",
  "mogelbaum": "Sudowoodo",
  "sonnflora": "Sunflora",
  "sonnkern": "Sunkern",
  "gehweiher": "Surskit",
  "wablu": "Swablu",
  "folikon": "Swadloon",
  "schlukwech": "Swalot",
  "sumpex": "Swampert",
  "swaroness": "Swanna",
  "schwalboss": "Swellow",
  "quiekel": "Swinub",
  "flauschling": "Swirlix",
  "fletiamo": "Swoobat",
  "feelinara": "Sylveon",
  "blipp": "Tadbulb",
  "schwalbini": "Taillow",
  "fiaro": "Talonflame",
  "zwieps": "Tandemaus",
  "tangoloss": "Tangrowth",
  "kapu-toro": "Tapu Bulu",
  "kapu-kime": "Tapu Fini",
  "kapu-riki": "Tapu Koko",
  "kapu-fala": "Tapu Lele",
  "tarundel": "Tarountula",
  "nigiragi": "Tatsugiri",
  "tentacha": "Tentacool",
  "tentoxa": "Tentacruel",
  "floink": "Tepig",
  "terrakium": "Terrakion",
  "gaunux": "Thievul",
  "jiutesto": "Throh",
  "voltolos": "Thundurus",
  "chimstix": "Thwackey",
  "praktibalk": "Timburr",
  "dinglu": "Ting-Lu",
  "forgita": "Tinkatink",
  "granforgita": "Tinkaton",
  "tafforgita": "Tinkatuff",
  "galapaflos": "Tirtouga",
  "tentagra": "Toedscool",
  "tenterra": "Toedscruel",
  "flemmli": "Torchic",
  "qurtel": "Torkoal",
  "boreos": "Tornadus",
  "miezunder": "Torracat",
  "chelterrar": "Torterra",
  "karnimani": "Totodile",
  "tukanon": "Toucannon",
  "aggrostella": "Toxapex",
  "toxiquak": "Toxicroak",
  "riffex": "Toxtricity",
  "navitaub": "Tranquill",
  "knacklion": "Trapinch",
  "geckarbor": "Treecko",
  "trombork": "Trevenant",
  "unratütox": "Trubbish",
  "trompeck": "Trumbeak",
  "fruyal": "Tsareena",
  "tortunator": "Turtonator",
  "chelast": "Turtwig",
  "schallquap": "Tympole",
  "zapplardin": "Tynamo",
  "typ:null": "Type: Null",
  "type null": "Type: Null",
  "typenull": "Type: Null",
  "tornupto": "Typhlosion",
  "despotar": "Tyranitar",
  "monargoras": "Tyrantrum",
  "rabauz": "Tyrogue",
  "balgoras": "Tyrunt",
  "nachtara": "Umbreon",
  "fasasnob": "Unfezant",
  "icognito": "Unown",
  "wulaosu": "Urshifu",
  "selfe": "Uxie",
  "gelatroppo": "Vanillish",
  "gelatini": "Vanillite",
  "gelatwino": "Vanilluxe",
  "aquana": "Vaporeon",
  "knattox": "Varoom",
  "agiluza": "Veluza",
  "toxiped": "Venipede",
  "omot": "Venomoth",
  "bluzuk": "Venonat",
  "bisaflor": "Venusaur",
  "honweisel": "Vespiquen",
  "sarzenia": "Victreebel",
  "muntier": "Vigoroth",
  "donarion": "Vikavolt",
  "giflor": "Vileplume",
  "viridium": "Virizion",
  "ramoth": "Volcarona",
  "voltobal": "Voltorb",
  "skallyk": "Vullaby",
  "vulpix": "Vulpix",
  "windewoge": "Walking Wake",
  "walraisa": "Walrein",
  "schillok": "Wartortle",
  "kukmarda": "Watchog",
  "voltrel": "Wattrel",
  "snibunna": "Weavile",
  "hornliu": "Weedle",
  "ultrigaria": "Weepinbell",
  "smogmog": "Weezing",
  "elfun": "Whimsicott",
  "rollum": "Whirlipede",
  "welsar": "Whiscash",
  "flurmel": "Whismur",
  "knuddeluff": "Wigglytuff",
  "schligda": "Wiglett",
  "reißlaus": "Wimpod",
  "lusardin": "Wishiwashi",
  "chongjian": "Wo-Chien",
  "woingenau": "Wobbuffet",
  "fleknoil": "Woobat",
  "wolly": "Wooloo",
  "felino": "Wooper",
  "burmadame": "Wormadam",
  "schligdri": "Wugtrio",
  "waumpel": "Wurmple",
  "isso": "Wynaut",
  "damythir": "Wyrdeer",
  "voltriant": "Xurkitree",
  "makabaja": "Yamask",
  "voldi": "Yamper",
  "mangunior": "Yungoos",
  "sengo": "Zangoose",
  "zebritz": "Zebstrika",
  "zigzachs": "Zigzagoon",
  "duodino": "Zweilous",
};

/**
 * Translates a German Pokémon name (or a name containing a German Pokémon name)
 * to the corresponding English name. Returns the translated string if a German
 * name was found, or null if no translation is available.
 *
 * Examples:
 *   translateGermanName('Glurak')      → 'Charizard'
 *   translateGermanName('Glurak EX')   → 'Charizard EX'
 *   translateGermanName('Bisasam V')   → 'Bulbasaur V'
 *   translateGermanName('Charizard')   → null  (already English)
 *   translateGermanName('mewtu')       → 'Mewtwo'
 */
export function translateGermanName(query: string): string | null {
  const trimmed = query.trim();
  if (!trimmed) return null;

  // Try full query first (handles names with spaces like "Mr. Mime")
  const fullLower = trimmed.toLowerCase();
  if (DE_TO_EN[fullLower]) return DE_TO_EN[fullLower]!;

  // Split and try first token, preserving any suffix (EX, GX, V, VMAX …)
  const tokens = trimmed.split(/\s+/);
  if (tokens.length === 0) return null;

  const firstName = tokens[0]!;
  const firstLower = firstName.toLowerCase();

  if (DE_TO_EN[firstLower]) {
    const englishName = DE_TO_EN[firstLower]!;
    const rest = tokens.slice(1).join(' ');
    return rest ? `${englishName} ${rest}` : englishName;
  }

  // Try first two tokens (e.g. "Mr Mime" written without a dot)
  if (tokens.length >= 2) {
    const twoTokensLower = `${tokens[0]} ${tokens[1]}`.toLowerCase();
    if (DE_TO_EN[twoTokensLower]) {
      const englishName = DE_TO_EN[twoTokensLower]!;
      const rest = tokens.slice(2).join(' ');
      return rest ? `${englishName} ${rest}` : englishName;
    }
  }

  return null;
}

/**
 * Same as translateGermanName but also tries fuzzy / prefix matching.
 * Used by the scanner where OCR may produce slightly garbled text.
 *
 * Fuzzy rules:
 *  1. Forward: OCR appended noise   – "garadosu" starts with DB key "garados" → Gyarados
 *  2. Reverse: OCR truncated name   – "karpado" is prefix of DB key "karpador" (≤2 chars short) → Magikarp
 */
export function fuzzyTranslateGermanName(query: string): string | null {
  // Try exact match first
  const exact = translateGermanName(query);
  if (exact !== null) return exact;

  const trimmed = query.trim();
  if (!trimmed) return null;
  const tokens = trimmed.split(/\s+/);
  const firstName = tokens[0]!;
  const firstLower = firstName.toLowerCase();
  if (firstLower.length < 3) return null;

  const suffix = tokens.slice(1).join(' ');

  // 1. Forward prefix: OCR text starts with a known DB key ("garadosu" → "garados")
  for (const [key, english] of Object.entries(DE_TO_EN)) {
    if (key.length >= 4 && firstLower.startsWith(key)) {
      return suffix ? `${english} ${suffix}` : english;
    }
  }

  // 2. Reverse prefix: known DB key starts with OCR text (OCR cut off ≤2 chars)
  if (firstLower.length >= 4) {
    for (const [key, english] of Object.entries(DE_TO_EN)) {
      if (key.length > firstLower.length && key.length - firstLower.length <= 2 && key.startsWith(firstLower)) {
        return suffix ? `${english} ${suffix}` : english;
      }
    }
  }

  return null;
}
